version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tigrinho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
